language: android
sudo: false
notifications:
  email: false

before_install:
  - yes | sdkmanager "platforms;android-27"

script: ./CI/travis.sh

android:
  components:
    - tools
    - build-tools-27.1.1
    - platform-tools
    - tools
    - android-27
